### PR TITLE
Fix error group highlighting under cursorline.

### PR DESCRIPTION
**Pull request by cherrry**
# Description

Fix the error-related highlight groups when interacting with cursorline.

Before the fix, when there's error in the line you're editing, the highlight conflicted and the words can't be read:

before

After:

after

And for light theme after the fix:

after (light)

If there're other known groups having the same issue, please let me know and I'm happy to fix them in the same PR, as I just fixed a few highlight groups that I suffered from.

# Checklist

- [x] I have built the project after my changes following [the build instructions](https://github.com/fnune/base16-vim#building) using `make`
- [x] I have confirmed that my changes produce no regressions after building
- [x] I have pushed the built files to this pull request

### CODE REVIEW

**Comment by fnune** [comment]
Thank you!

**Comment by GordianDziwis** [comment]
@fnune Can you revert this? With the GUI highlights it breaks all the errors:

image

With the GUI errors are just undercurled or underlined, using the reverse modifier breaks this and also changes the fg and bg.

For the same reason, when underlined is used, no fg and bg should be set for the gui.

**Comment by cherrry** [comment]
@BonaBeavis I authored the PR because when error highlighted on the line where cursor was, I couldn't read the words at all.

For the case you mentioned, maybe I've overdone the `ErrorHighlight` and few of its sibling groups?
https://github.com/fnune/base16-vim/blob/master/templates/default.mustache#L288-L296

**Comment by fnune** [comment]
I tested around with my setup before merging that PR and I saw no problems. I think I need to learn how too foresee these things, I'm a bit ignorant to Vimscript, to be honest.

It sounds like a reversal isn't necessary and we can just patch up the changes?

Or perhaps @cherrry you could checkk that the theme you're using isn't at fault and it's assigning the wrong colors?

**Comment by fnune** [comment]
I've changed my mind and gone ahead and reverted the changes, since I did find some breakage after more careful inspection, and the cases where it's broken seem more normal than what the initial fix was trying to fix.

**Comment by GordianDziwis** [comment]
I think the difference with your setup is, that you are using the terminal highlights.

Maybe it is possible to create a test file and take a screenshot of this test file after the build? [macos - Can we capture a screenshot of vim window using Terminal? - Ask Different](https://apple.stackexchange.com/questions/334141/can-we-capture-a-screenshot-of-vim-window-using-terminal)

**Pull request merged**
