### PR TITLE
Add Base24 template support and rename repo to tinted-vim

### PR DESCRIPTION
**Pull request by JamyGolden**
## Description

- Add Base24 template support and rename repo to tinted-vim
- Require PRs to include built files in separate commit

## Checklist

- [x] I have included the built files `./colors/*.vim` in a separate commit and followed [the build instructions](https://github.com/tinted-theming/tinted-vim/blob/main/CONTRIBUTING.md)
- [x] I have confirmed that my changes produce no regressions after building

### CODE REVIEW

**Comment by JamyGolden** [comment]
Since you've created a PR recently @AntoinePrv it would be great if you could glance over at least the `templates/base16.mustache` to make sure there aren't any breaking changes. Any feedback is welcome!

**Comment by GordianDziwis** [comment]
Having a template for base16 and base24 is a lot of duplication. Is it feasible to have just the base24 template and then define a mapping from the 16 base16 colors to the 24 base24 colors?

**Comment by JamyGolden** [comment]
I could change things to have a single template we work on for all theme systems. I'd have to create variables for every value though, so we don't style directly with `gui08` and instead have `let s:syntax_class = "#{{palette.base08}}`. That way the variable values can be set from the theme system.

**Comment by RobLoach** [comment]
@JamyGolden Looks like the bot caused some conflicts with its latest scheme update. Would you like some help on a rebase here? Happy to help out.

**Comment by JamyGolden** [comment]
Thanks @RobLoach I've just fixed the conflict.

@GordianDziwis we're discussing ways we can extend the base16 specification. These values would make it a lot easier to have a consistent theme for both base16 and base24 template variants since the template could simply apply those values instead of `{{base0x-hex}}` values and templates can be shared. I think it would be good to get base24 themes in now though, so I think we should merge this with the understanding that we will find a way to unify the theming since editor themes are a lot more complex than general shells and cli tools. https://github.com/tinted-theming/home/pull/99#discussion_r1779474977

**Review by GordianDziwis — APPROVED** [review]
Merge it. I have made based on this commit a complete overhaul of the mustache templates. I will create today a merge request.

**Pull request merged**
