### PR TITLE
Fix float background

### LINKED ISSUE #39: [Bug report] Background colors too light for nvim-cmp?
**Describe the bug**
It's hard to read things in autocomplete menus

**Expected behavior**
A dark background (like the one in https://github.com/fnune/base16-vim/pull/38 ? )

**Screenshots**

**System**
Neovim version: v0.5.1
Any other plugins you may consider relevant: https://github.com/hrsh7th/nvim-cmp

**Minimal configuration file**
```lua
local o = vim.o

g.colors_name = 'base16-solarized-dark'
o.termguicolors = true
```

**Additional context**
I have enabled `termguicolors` otherwise it was really ugly. I'm using Alacritty configured as followed:

```
# Colors (Solarized Dark)
colors:
  # Default colors
  primary:
    background: '0x002b36'
    foreground: '0x839496'

  # Normal colors
  normal:
    black:   '0x073642'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xd33682'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'

  # Bright colors
  bright:
    black:   '0x002b36'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'
```

### PR DESCRIPTION
**Pull request by GordianDziwis**
# Description

See https://github.com/fnune/base16-vim/pull/38

# Checklist

- [x] I have built the project after my changes following [the build
  instructions](https://github.com/fnune/base16-vim/blob/master/CONTRIBUTING.md#building)
  using `make`
- [x] I have confirmed that my changes produce no regressions after building
- [x] I have pushed the built files to this pull request

### CODE REVIEW

**Comment by greg0ire** [comment]
Hi! I've been using your branch locally, and I think maybe we should also use that darker background color for diffs? The light green is a bit hard to read here…

**Comment by GordianDziwis** [comment]
> Hi! I've been using your branch locally, and I think maybe we should also use that darker background color for diffs? The light green is a bit hard to read here…
> 

The issue is that with the darker background, the diff has the same background as the folding row, this would make the diff harder to read for all colorschemes.

**Comment by greg0ire** [comment]
Then maybe the font needs to be changed to be darker when highlighted?

**Comment by GordianDziwis** [comment]
@greg0ire check this out https://github.com/fnune/base16-vim/pull/43

**Review by fnune — APPROVED** [review]
@BonaBeavis I'm no longer using `base16-vim`. Should I give you full access to the repo? I'm hardly able to review these PRs.

**Comment by GordianDziwis** [comment]
@fnune yeah, sounds reasonable. What are you using now?

**Comment by fnune** [comment]
Just realized you already have the maximum amount of permissions available in a user-owned (vs organization-owned) repository: Collaborator.

So feel free to merge without my approval, although I'll take a look at things when I can.

I've been trying out [Falcon](https://github.com/fenetikm/falcon) and [Rose Pine](https://github.com/rose-pine/), both of which have variants for most of the apps I use.

I'll probably come back to `base16-vim` one day though, especially seeing all the love it's getting :slightly_smiling_face:

**Pull request merged**
