### PR TITLE
Rework highligts

### LINKED ISSUE #68: [Bug report] base16-material.vim broken as of latest release
## Describe the bug

With yesterday's update at the very least `base16-material.vim` seems to be broken - launching vim yields the following error:

```
line  411:
W18: Invalid character in group name
line  412:
W18: Invalid character in group name
line  413:
W18: Invalid character in group name
line  414:
W18: Invalid character in group name
line  415:
W18: Invalid character in group name
line  416:
W18: Invalid character in group name
line  420:
W18: Invalid character in group name
line  421:
W18: Invalid character in group name
line  431:
W18: Invalid character in group name
line  434:
W18: Invalid character in group name
line  435:
W18: Invalid character in group name
```

## Expected behavior

vim loads without any errors by themes added via `base16-vim`.

## **System**

**Vim or Neovim:**

Vim

**Vim or Neovim version:**

9.0.1000

**Any other plugins you may consider relevant:**

N/A

## Minimal configuration file

No configuration file needed, loading the plugin itself is sufficient to trigger the bug (the theme does not even need to be selected as the error occurs in `vim90/syntax/synload.vim[19]`.

## Additional context

N/A

### PR DESCRIPTION
**Pull request by GordianDziwis**
# Description

I made the highlights less red. 

Fixes #68
# Checklist

- [x] I have built the project after my changes following [the build
  instructions](https://github.com/tinted-theming/base16-vim/blob/main/CONTRIBUTING.md#building)
  using `make`
- [x] I have confirmed that my changes produce no regressions after building
- [x] I have pushed the built files to this pull request

### CODE REVIEW

**Review by JamyGolden — APPROVED** [review]
Nice!

**Comment by nbn22385** [comment]
@BonaBeavis I noticed the `Comment` highlight group now has the `italic` attribute. This had the effect of giving all my comments a background color (which I then disabled with a highlight override). Did you encounter this or could it be some other configuration issue on my system?

**Comment by GordianDziwis** [comment]
Should be an Issue on your system. I use `:TSHighlightCapturesUnderCursor` and `:Telescope highlights` for debugging. Maybe you can pin it down

**Comment by nbn22385** [comment]
I noticed this was only happening in tmux. Ultimately changing `default-terminal` from `screen-256color` to `tmux-256color` did the trick. There must have been a recent update that required me to change that.

**Pull request merged**
